[book]
authors = ["Maxim Kim"]
description = "База знаний."
language = "ru"
multilingual = false
src = "src"

[build]
build-dir = "docs"
create-missing = false

[output.html.playpen]
copyable = false
editable = true

[output.html.fold]
enable = true