[book]
authors = ["Maxim Kim"]
description = "База знаний."
language = "ru"
multilingual = false
src = "src"

[output.html]
default-theme = "ayu"

[output.html.playpen]
copyable = false
editable = true

[output.html.fold]
enable = true